version: '3.3'
services:

  db:
    container_name: megahit_db
    restart: always
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - '3306:3306' # Host port 3306 assigned to container port 3306
    expose:
      - '3306' # Note: 3306 is the default port for MySQL
    volumes:
      - data-volume:/var/lib/mysql

  app:
    container_name: megahit_app
    restart: always # TODO: Change restart policy
    env_file: ./.env
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:mysql://megahit_db:3306/megahitdb
      - spring.datasource.username=megahit_user
      - spring.datasource.password=1234
      - spring.jpa.show-sql=true
      - server.servlet.context-path=/api/v1
    stdin_open: true
    tty: true

networks:
  default:
    name: megahit_backend
volumes:
  data-volume:

# Useful commands:
# docker-compose __ (up, down, start, stop, pause, unpause)

# For a fresh start:
# docker system prune -a
# docker volume prune
# docker network prune