version: '3.3'
services:

  db:
    container_name: megahit_db
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: 'megahitdb'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306' # Host port 3306 assigned to container port 3306
    expose:
      - '3306' # Note: 3306 is the default port for MySQL
    volumes:
      - data-volume:/var/lib/mysql

networks:
  default:
    name: megahit_backend
volumes:
  data-volume:

# Useful commands:
# docker-compose __ (up, down, start, stop, pause, unpause)

# For a fresh start:
# docker system prune -a
# docker volume prune
# docker network prune