package com.megahit.backend.Account;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/account") // This means URL's start with /account (after Application path)
@CrossOrigin(origins = "http://localhost:3000")
public class AccountController {
    @Autowired // This means to get the bean called accountRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;
    private AccountService accountService;

    public AccountController(AccountService accountService) {this.accountService = accountService;}

    @GetMapping(path="")
    public @ResponseBody Boolean attemptLogin(@RequestParam String emailAddress, @RequestParam String account_password) {
        return accountService.checkIfValidLogin(emailAddress, account_password);
    }
}
