package com.megahit.backend.Account;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/account") // This means URL's start with /account (after Application path)
@CrossOrigin(origins = "http://localhost:3000")
public class AccountController {
    @Autowired // This means to get the bean called accountRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Account> getAllAccounts() {
        // This returns a JSON or XML with the users
        return accountRepository.findAll();
    }

    @GetMapping(path="")
    public @ResponseBody Account getAccountByEmailAddress(@RequestParam String emailAddress) {
        return accountRepository.findByEmailAddress(emailAddress);
    }
}
